version: '3.7'
services:

  lrp-db:
    container_name: lrp-db
    image: 'postgres:latest'
    env_file:
      - ".env"
    environment:
      POSTGRES_PASSWORD: ${DB_ADMIN_PASS}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "54322:5432"
    networks:
      - lprnetwork

  lrp-backend:
    container_name: lrp-backend
    build:
      context: ./backend
    networks:
      - lprnetwork
    ports:
      - '9002:9000'
    volumes:
      - ./backend:/var/www
    depends_on:
      - lrp-db

  lrp-nginx:
    container_name: lrp-nginx
    build:
      context: ./nginx
    volumes:
      - ./backend/public:/var/www/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - lrp-backend
    ports:
      - "8050:8050"
    networks:
      - lprnetwork


  lrp-frontend:
    container_name: lrp-frontend
    build:
      context: ./frontend
    tty: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - lrp-backend
    networks:
      - lprnetwork

networks:
  lprnetwork:
    driver: bridge
    